### ISSUE TITLE
Though I've install import_ipynb, I'm facing this issue after running the first cell of Sudoku Testing on jupyter

### ISSUE THREAD

**Issue by asitsonawane** [snehitvaddi/Real-Time-Sudoku-Solver-OpenCV-and-Keras#1]
![Screenshot_2020-06-21 sudoku testing - Jupyter Notebook](https://user-images.githubusercontent.com/57346660/85227339-78512080-b3fa-11ea-83b8-bae0c107fe5d.png)
I'm a beginner and I'm trying this out but I don't understand what I should do next.

**Comment by snehitvaddi** [comment]
@asitsonawane use `pip install import_ipynb`. After installing all the required package, just run all cells of sudoku_tester without running other files.

**Comment by snehitvaddi** [comment]
@asitsonawane instead of installing each package individually, directly run `pip install -r requirements.txt`. I have updated the required packages.

**Comment by asitsonawane** [comment]
It gave out this after installing keras and numpy
and i already have opencv 4.2


ERROR: Could not find a version that satisfies the requirement opencv-python==4.1.2 (from -r requirements.txt (line 3)) (from versions: 3.4.8.29, 3.4.9.31, 3.4.9.33, 4.1.2.30, 4.2.0.32, 4.2.0.34)                                                                                                                                                     ERROR: No matching distribution found for opencv-python==4.1.2 (from -r requirements.txt (line 3))

**Comment by snehitvaddi** [comment]
Have you tried installing that package individually? 
If yes, and still facing the same problem refer to [this thread ](https://stackoverflow.com/questions/45293933/could-not-find-a-version-that-satisfies-the-requirement-opencv-python). You might find some solution!!

Or try installing opencv-python==4.2.0.34
Edit: Sorry!! that's my spelling mistake in requirements.txt file. Now, I updated it😁

**Comment by asitsonawane** [comment]
Yes. I installed all the requirements individually, I checked if they're installed, specially import_ipynb, and it is. Restarted kernel, still the same issue.

![import](https://user-images.githubusercontent.com/57346660/85228707-9c186480-b402-11ea-831a-c62010b2bbbe.JPG)

**Comment by snehitvaddi** [comment]
So still, you are facing `ERROR: Could not find a version that satisfies the requirement opencv-python==4.1.2` right!!
then, please refer to some relevant threads on StackOverflow and Github issues. I too don't know why is it raising and meanwhile I will also check it. I will share it with you if I find a solution.

**Comment by asitsonawane** [comment]
Nope not opencv... It says import_ipynb module isn't available... Is there any other way that could do the work which import_ipynb does.

**Comment by asitsonawane** [comment]
I used "nbimporter" instead of "import_ipynb" and it got solved.
