### ISSUE TITLE
Unable to import sudokuSolver in RealTimeSudokuSolver notebook.

### ISSUE THREAD

**Issue by asitsonawane** [snehitvaddi/Real-Time-Sudoku-Solver-OpenCV-and-Keras#2]
Everything works well but because its unable to import sudokuSolver, it doesn't show the solution on screen and doesnt detect the sudoku.

![Screenshot_2020-06-22 RealTimeSudokuSolver - Jupyter Notebook](https://user-images.githubusercontent.com/57346660/85233534-b6fbd080-b424-11ea-952c-2d8268cdff2e.png)

**Comment by snehitvaddi** [comment]
Since we are using jupyter notebooks ie;**.ipynb files**, there are some issues in importing, so I have included a code like `%run sudokuSolver` which interprets all the cells in sudokuSolver file ignoring some errors. So you just need to run sudoku_testing without running any other files.

**Comment by asitsonawane** [comment]
Okayy, thankyou for answering so many questions patiently 😅
